"""Manage ~/.config/hypr/hyprgui.conf and the source line in hyprland.conf."""

from __future__ import annotations

import os
from pathlib import Path

from hyprgui.settings_registry import SETTINGS, SettingDef, SettingType

HYPR_DIR = Path.home() / ".config" / "hypr"
HYPRGUI_CONF = HYPR_DIR / "hyprgui.conf"
HYPRLAND_CONF = HYPR_DIR / "hyprland.conf"
SOURCE_LINE = f"source = {HYPRGUI_CONF}"


def is_source_line_present() -> bool:
    """Check whether hyprland.conf already sources our config."""
    if not HYPRLAND_CONF.exists():
        return False
    text = HYPRLAND_CONF.read_text()
    for line in text.splitlines():
        stripped = line.strip()
        if stripped == SOURCE_LINE or stripped == f"source={HYPRGUI_CONF}":
            return True
    return False


def create_empty_conf() -> None:
    """Create an empty hyprgui.conf so Hyprland doesn't error on source."""
    HYPR_DIR.mkdir(parents=True, exist_ok=True)
    if not HYPRGUI_CONF.exists():
        HYPRGUI_CONF.write_text("# Generated by Hyprgui — do not edit manually\n")


def append_source_line() -> None:
    """Append the source line to hyprland.conf and create the conf file."""
    create_empty_conf()
    with open(HYPRLAND_CONF, "a") as f:
        f.write(f"\n# Added by Hyprgui\n{SOURCE_LINE}\n")


def write_hyprgui_conf(values: dict[str, object]) -> None:
    """Write all current settings to hyprgui.conf atomically.

    Uses Hyprland's native section syntax:
        section {
            key = value
        }
    """
    sections: dict[str, list[str]] = {}

    for sdef in SETTINGS:
        val = values.get(sdef.key)
        if val is None:
            continue
        formatted = _format_conf_value(sdef, val)
        parts = sdef.key.split(":")
        if len(parts) == 1:
            section_path = ""
            var_name = parts[0]
        else:
            section_path = ":".join(parts[:-1])
            var_name = parts[-1]

        sections.setdefault(section_path, []).append(f"{var_name} = {formatted}")

    lines = ["# Generated by Hyprgui — do not edit manually", ""]

    for section_path, entries in sections.items():
        if not section_path:
            for entry in entries:
                lines.append(entry)
            lines.append("")
            continue

        parts = section_path.split(":")
        # Build nested sections
        for i, part in enumerate(parts):
            lines.append("    " * i + part + " {")
        indent = "    " * len(parts)
        for entry in entries:
            lines.append(indent + entry)
        for i in range(len(parts) - 1, -1, -1):
            lines.append("    " * i + "}")
        lines.append("")

    tmp_path = HYPRGUI_CONF.with_suffix(".tmp")
    HYPR_DIR.mkdir(parents=True, exist_ok=True)
    tmp_path.write_text("\n".join(lines))
    tmp_path.rename(HYPRGUI_CONF)


def _format_conf_value(sdef: SettingDef, value: object) -> str:
    """Format a value for the Hyprland config file."""
    if sdef.setting_type == SettingType.BOOL:
        return "true" if value else "false"
    if sdef.setting_type == SettingType.INT:
        return str(int(value))
    if sdef.setting_type == SettingType.FLOAT:
        return f"{float(value):.6f}".rstrip("0").rstrip(".")
    if sdef.setting_type == SettingType.COLOR:
        return f"rgba({value})"
    return str(value)
