"""Manage ~/.config/hypr/hyprgui.conf and the source line in hyprland.conf."""

from __future__ import annotations

import os
from pathlib import Path

from hyprgui.settings_registry import SETTINGS, SettingDef, SettingType

HYPR_DIR = Path.home() / ".config" / "hypr"
HYPRGUI_CONF = HYPR_DIR / "hyprgui.conf"
HYPRLAND_CONF = HYPR_DIR / "hyprland.conf"
SOURCE_LINE = f"source = {HYPRGUI_CONF}"


def is_source_line_present() -> bool:
    """Check whether hyprland.conf already sources our config."""
    if not HYPRLAND_CONF.exists():
        return False
    text = HYPRLAND_CONF.read_text()
    for line in text.splitlines():
        stripped = line.strip()
        if stripped == SOURCE_LINE or stripped == f"source={HYPRGUI_CONF}":
            return True
    return False


def create_empty_conf() -> None:
    """Create an empty hyprgui.conf so Hyprland doesn't error on source."""
    HYPR_DIR.mkdir(parents=True, exist_ok=True)
    if not HYPRGUI_CONF.exists():
        HYPRGUI_CONF.write_text("# Generated by Hyprgui — do not edit manually\n")


def append_source_line() -> None:
    """Append the source line to hyprland.conf and create the conf file."""
    create_empty_conf()
    with open(HYPRLAND_CONF, "a") as f:
        f.write(f"\n# Added by Hyprgui\n{SOURCE_LINE}\n")


def reset_hyprgui_conf() -> None:
    """Clear hyprgui.conf to an empty stub so the user's own config takes over."""
    HYPR_DIR.mkdir(parents=True, exist_ok=True)
    HYPRGUI_CONF.write_text("# Generated by Hyprgui — do not edit manually\n")


def parse_hyprgui_conf() -> set[str]:
    """Parse hyprgui.conf and return the set of setting keys it manages."""
    if not HYPRGUI_CONF.exists():
        return set()

    keys: set[str] = set()
    section_stack: list[str] = []

    for line in HYPRGUI_CONF.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue

        # Cursor env vars → sentinel keys
        if stripped.startswith("env = HYPRCURSOR_THEME,") or stripped.startswith("env = XCURSOR_THEME,"):
            keys.add("_cursor_theme")
            continue
        if stripped.startswith("env = HYPRCURSOR_SIZE,") or stripped.startswith("env = XCURSOR_SIZE,"):
            keys.add("_cursor_size")
            continue

        # `monitor = ...` lines are tracked separately via parse_managed_monitors().
        if stripped.startswith("monitor"):
            continue

        # Section open
        if stripped.endswith("{"):
            section_stack.append(stripped[:-1].strip())
            continue

        # Section close
        if stripped == "}":
            if section_stack:
                section_stack.pop()
            continue

        # key = value
        if "=" in stripped:
            key_part = stripped.split("=", 1)[0].strip()
            full_key = ":".join(section_stack + [key_part]) if section_stack else key_part
            keys.add(full_key)

    return keys


def parse_managed_monitors() -> dict[str, str]:
    """Return ``{monitor_name: full_spec_string}`` for monitors saved by Hyprgui.

    Reads ``monitor = <name>,<spec>`` lines from hyprgui.conf and returns them
    keyed by name. Used to persist Display page changes across reloads.
    """
    if not HYPRGUI_CONF.exists():
        return {}

    out: dict[str, str] = {}
    for line in HYPRGUI_CONF.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not stripped.startswith("monitor"):
            continue
        # `monitor = NAME,...` or `monitor=NAME,...`
        eq = stripped.find("=")
        if eq < 0:
            continue
        spec = stripped[eq + 1:].strip()
        first_comma = spec.find(",")
        if first_comma < 0:
            continue
        name = spec[:first_comma].strip()
        if name and not name.startswith("disable") and name != "":
            out[name] = spec
    return out


def write_hyprgui_conf(
    values: dict[str, object],
    *,
    managed_keys: set[str] | None = None,
    cursor_theme: str = "",
    cursor_size: int = 0,
    monitors: dict[str, str] | None = None,
) -> None:
    """Write managed settings to hyprgui.conf atomically.

    Uses Hyprland's native section syntax:
        section {
            key = value
        }
    """
    sections: dict[str, list[str]] = {}

    for sdef in SETTINGS:
        if managed_keys is not None and sdef.key not in managed_keys:
            continue
        val = values.get(sdef.key)
        if val is None:
            continue
        formatted = _format_conf_value(sdef, val)
        parts = sdef.key.split(":")
        if len(parts) == 1:
            section_path = ""
            var_name = parts[0]
        else:
            section_path = ":".join(parts[:-1])
            var_name = parts[-1]

        sections.setdefault(section_path, []).append(f"{var_name} = {formatted}")

    lines = ["# Generated by Hyprgui — do not edit manually", ""]

    # Monitor lines (must come before sections so window rules etc. that
    # reference them resolve correctly).
    if monitors:
        lines.append("# Monitors")
        for name, spec in monitors.items():
            lines.append(f"monitor = {spec}")
        lines.append("")

    # Cursor theme env vars (must be set before other sections)
    if cursor_theme:
        lines.append(f"env = HYPRCURSOR_THEME,{cursor_theme}")
        lines.append(f"env = XCURSOR_THEME,{cursor_theme}")
    if cursor_size:
        lines.append(f"env = HYPRCURSOR_SIZE,{cursor_size}")
        lines.append(f"env = XCURSOR_SIZE,{cursor_size}")
    if cursor_theme or cursor_size:
        lines.append("")

    for section_path, entries in sections.items():
        if not section_path:
            for entry in entries:
                lines.append(entry)
            lines.append("")
            continue

        parts = section_path.split(":")
        # Build nested sections
        for i, part in enumerate(parts):
            lines.append("    " * i + part + " {")
        indent = "    " * len(parts)
        for entry in entries:
            lines.append(indent + entry)
        for i in range(len(parts) - 1, -1, -1):
            lines.append("    " * i + "}")
        lines.append("")

    tmp_path = HYPRGUI_CONF.with_suffix(".tmp")
    HYPR_DIR.mkdir(parents=True, exist_ok=True)
    tmp_path.write_text("\n".join(lines))
    tmp_path.rename(HYPRGUI_CONF)


def upsert_managed_monitors(updates: dict[str, str]) -> None:
    """Merge ``updates`` into the managed monitor block and rewrite the file.

    Preserves all other content (settings, cursor env vars) by re-reading
    them from disk. Used by the Display page so monitor changes survive
    ``hyprctl reload``.
    """
    existing = parse_managed_monitors()
    existing.update(updates)

    managed_keys = parse_hyprgui_conf()
    values = _read_existing_values(managed_keys)
    cursor_theme, cursor_size = _read_existing_cursor()

    write_hyprgui_conf(
        values,
        managed_keys=managed_keys,
        cursor_theme=cursor_theme,
        cursor_size=cursor_size,
        monitors=existing,
    )


def _read_existing_values(managed_keys: set[str]) -> dict[str, object]:
    """Re-parse hyprgui.conf to recover typed values for SettingDef keys."""
    if not HYPRGUI_CONF.exists():
        return {}

    raw: dict[str, str] = {}
    section_stack: list[str] = []
    for line in HYPRGUI_CONF.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("env =") or stripped.startswith("monitor"):
            continue
        if stripped.endswith("{"):
            section_stack.append(stripped[:-1].strip())
            continue
        if stripped == "}":
            if section_stack:
                section_stack.pop()
            continue
        if "=" in stripped:
            k, v = stripped.split("=", 1)
            full = ":".join(section_stack + [k.strip()]) if section_stack else k.strip()
            raw[full] = v.strip()

    values: dict[str, object] = {}
    for sdef in SETTINGS:
        if sdef.key not in managed_keys:
            continue
        s = raw.get(sdef.key)
        if s is None:
            continue
        values[sdef.key] = _coerce_conf_value(sdef, s)
    return values


def _coerce_conf_value(sdef: SettingDef, raw: str) -> object:
    """Best-effort string → typed value (inverse of _format_conf_value)."""
    try:
        if sdef.setting_type == SettingType.BOOL:
            return raw.lower() in ("true", "1", "yes")
        if sdef.setting_type == SettingType.INT:
            return int(raw)
        if sdef.setting_type == SettingType.FLOAT:
            return float(raw)
        if sdef.setting_type == SettingType.COLOR:
            # rgba(RRGGBBAA) → RRGGBBAA
            if raw.startswith("rgba(") and raw.endswith(")"):
                return raw[5:-1]
            return raw
        if sdef.setting_type == SettingType.ENUM and sdef.enum_values:
            if raw in sdef.enum_values:
                return sdef.enum_options[sdef.enum_values.index(raw)]
            return raw
    except (ValueError, IndexError):
        pass
    return raw


def _read_existing_cursor() -> tuple[str, int]:
    """Recover cursor theme/size from env lines in hyprgui.conf."""
    if not HYPRGUI_CONF.exists():
        return "", 0
    theme = ""
    size = 0
    for line in HYPRGUI_CONF.read_text().splitlines():
        stripped = line.strip()
        if stripped.startswith("env = HYPRCURSOR_THEME,") or stripped.startswith("env = XCURSOR_THEME,"):
            theme = stripped.split(",", 1)[1].strip()
        elif stripped.startswith("env = HYPRCURSOR_SIZE,") or stripped.startswith("env = XCURSOR_SIZE,"):
            try:
                size = int(stripped.split(",", 1)[1].strip())
            except ValueError:
                pass
    return theme, size


def _format_conf_value(sdef: SettingDef, value: object) -> str:
    """Format a value for the Hyprland config file."""
    if sdef.setting_type == SettingType.BOOL:
        return "true" if value else "false"
    if sdef.setting_type == SettingType.INT:
        return str(int(value))
    if sdef.setting_type == SettingType.FLOAT:
        return f"{float(value):.6f}".rstrip("0").rstrip(".")
    if sdef.setting_type == SettingType.COLOR:
        return f"rgba({value})"
    if sdef.setting_type == SettingType.ENUM and sdef.enum_values:
        label = str(value)
        if label in sdef.enum_options:
            idx = sdef.enum_options.index(label)
            return sdef.enum_values[idx]
    return str(value)
