"""Write ``~/.config/hypr/hyprgui.lua`` for Lua-mode Hyprland (0.55+).

Mirrors :mod:`hyprgui.config_manager`'s role, but emits a Lua file that calls
``hl.config({...})`` for our managed settings. ``hl.config`` merges across calls
(verified on 0.55), so a ``dofile("hyprgui.lua")`` appended to ``hyprland.lua``
layers our managed subset on top of whatever else the user has.

State is also persisted to a JSON sidecar (``.hyprgui-state.json``) so we can
recover "which keys hyprgui manages" without parsing Lua back.
"""

from __future__ import annotations

import json

from hyprgui import lua_format
from hyprgui.config_mode import HYPR_DIR, HYPRGUI_LUA, HYPRLAND_LUA
from hyprgui.settings_registry import SETTINGS, SettingDef, SettingType

STATE_FILE = HYPR_DIR / ".hyprgui-state.json"

# How we link our file from the user's hyprland.lua. ``dofile`` with an absolute
# path is robust regardless of Lua's package.path, and ``hyprctl reload`` will
# re-run hyprland.lua (which re-runs us) on every save.
_LINK_LINE = f'dofile(os.getenv("HOME") .. "/.config/hypr/hyprgui.lua")'
_LINK_BANNER = "-- Added by Hyprgui — re-applies its managed settings"


# -- file existence / linking ----------------------------------------------

def hyprgui_lua_exists() -> bool:
    return HYPRGUI_LUA.exists()


def is_linked() -> bool:
    """True if ``hyprland.lua`` already ``dofile``s our file."""
    if not HYPRLAND_LUA.exists():
        return False
    text = HYPRLAND_LUA.read_text()
    return _LINK_LINE in text or "hyprgui.lua" in text  # tolerate hand-edited variants


def create_empty_lua() -> None:
    """Drop an empty stub so the user's ``dofile`` doesn't error before first save."""
    HYPR_DIR.mkdir(parents=True, exist_ok=True)
    if not HYPRGUI_LUA.exists():
        HYPRGUI_LUA.write_text("-- Generated by Hyprgui — do not edit manually\nhl.config({})\n")


def append_link_line() -> None:
    """Append the ``dofile`` line to ``hyprland.lua`` and create the stub file."""
    create_empty_lua()
    HYPRLAND_LUA.touch(exist_ok=True)
    with open(HYPRLAND_LUA, "a") as f:
        f.write(f"\n{_LINK_BANNER}\n{_LINK_LINE}\n")


def reset_hyprgui_lua() -> None:
    create_empty_lua()
    HYPRGUI_LUA.write_text("-- Generated by Hyprgui — do not edit manually\nhl.config({})\n")


# -- state sidecar ----------------------------------------------------------

def load_state() -> dict:
    """Read the sidecar JSON; on any error return an empty default."""
    if not STATE_FILE.exists():
        return {"managed_keys": [], "values": {}, "cursor_theme": "", "cursor_size": 0, "monitors": {}}
    try:
        return json.loads(STATE_FILE.read_text())
    except (OSError, json.JSONDecodeError):
        return {"managed_keys": [], "values": {}, "cursor_theme": "", "cursor_size": 0, "monitors": {}}


def save_state(state: dict) -> None:
    HYPR_DIR.mkdir(parents=True, exist_ok=True)
    tmp = STATE_FILE.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(state, indent=2, sort_keys=True))
    tmp.rename(STATE_FILE)


# -- value coercion ---------------------------------------------------------

def _coerce_state_value(sdef: SettingDef, raw: object) -> object:
    """JSON-loaded value -> typed value for the SettingDef."""
    try:
        if sdef.setting_type == SettingType.BOOL:
            return bool(raw)
        if sdef.setting_type == SettingType.INT:
            return int(raw)  # type: ignore[arg-type]
        if sdef.setting_type == SettingType.FLOAT:
            return float(raw)  # type: ignore[arg-type]
        return raw if raw is not None else sdef.default
    except (TypeError, ValueError):
        return sdef.default


# -- main write -------------------------------------------------------------

def write_hyprgui_lua(
    values: dict[str, object],
    *,
    managed_keys: set[str] | None = None,
    cursor_theme: str = "",
    cursor_size: int = 0,
    monitors: dict[str, str] | None = None,
) -> None:
    """Atomically rewrite ``hyprgui.lua`` and the state sidecar.

    The Lua file is regenerated from scratch each time (matches today's
    ``hyprgui.conf`` behavior). State persistence is via the sidecar JSON.
    """
    # Build the literals dict for hl.config from managed SettingDefs.
    literals: dict[str, str] = {}
    serialised_values: dict[str, object] = {}
    for sdef in SETTINGS:
        if managed_keys is not None and sdef.key not in managed_keys:
            continue
        val = values.get(sdef.key)
        if val is None:
            continue
        literals[lua_format.lua_path_for(sdef)] = lua_format.lua_value(sdef, val)
        serialised_values[sdef.key] = val

    parts: list[str] = ["-- Generated by Hyprgui — do not edit manually", ""]

    # Monitors via hl.monitor() — one call per monitor. The spec string
    # ``NAME,RESOLUTION,POS,SCALE`` from the Display page maps to MonitorSpec
    # fields: output, mode, position, scale.
    if monitors:
        parts.append("-- Monitors")
        for name, spec in monitors.items():
            parts.append(_monitor_call(name, spec))
        parts.append("")

    # Cursor env vars via hl.env (Lua equivalent of `env = X,Y`).
    if cursor_theme:
        parts.append(f'hl.env("HYPRCURSOR_THEME", {lua_format.lua_string(cursor_theme)})')
        parts.append(f'hl.env("XCURSOR_THEME", {lua_format.lua_string(cursor_theme)})')
    if cursor_size:
        parts.append(f'hl.env("HYPRCURSOR_SIZE", {lua_format.lua_string(str(cursor_size))})')
        parts.append(f'hl.env("XCURSOR_SIZE", {lua_format.lua_string(str(cursor_size))})')
    if cursor_theme or cursor_size:
        parts.append("")

    parts.append(lua_format.build_hl_config_call(literals))
    parts.append("")  # trailing newline

    HYPR_DIR.mkdir(parents=True, exist_ok=True)
    tmp = HYPRGUI_LUA.with_suffix(".lua.tmp")
    tmp.write_text("\n".join(parts))
    tmp.rename(HYPRGUI_LUA)

    save_state({
        "managed_keys": sorted(managed_keys) if managed_keys else sorted(serialised_values.keys()),
        "values": serialised_values,
        "cursor_theme": cursor_theme,
        "cursor_size": cursor_size,
        "monitors": monitors or {},
    })


def _monitor_call(name: str, spec: str) -> str:
    """Format a monitor spec line into an ``hl.monitor({...})`` call.

    Input shape: ``NAME,RESOLUTION,POSITION,SCALE`` (from the Display page).
    Anything not parsed falls through to a comment + raw spec for visibility.
    """
    parts = spec.split(",")
    # parts: NAME, RESOLUTION, POSITION, SCALE [, more...]
    out = f'output = {lua_format.lua_string(name)}'
    if len(parts) >= 2:
        out += f', mode = {lua_format.lua_string(parts[1].strip())}'
    if len(parts) >= 3:
        out += f', position = {lua_format.lua_string(parts[2].strip())}'
    if len(parts) >= 4:
        out += f', scale = {lua_format.lua_string(parts[3].strip())}'
    return f"hl.monitor({{ {out} }})"


def upsert_managed_monitors(updates: dict[str, str]) -> None:
    """Display-page entry point: merge monitor updates into existing state and rewrite."""
    state = load_state()
    monitors = dict(state.get("monitors") or {})
    monitors.update(updates)

    # Recover typed values from sidecar.
    values: dict[str, object] = {}
    raw_values = state.get("values") or {}
    by_key = {s.key: s for s in SETTINGS}
    for key, raw in raw_values.items():
        sdef = by_key.get(key)
        if sdef is not None:
            values[key] = _coerce_state_value(sdef, raw)
    managed_keys = set(state.get("managed_keys") or values.keys())

    write_hyprgui_lua(
        values,
        managed_keys=managed_keys,
        cursor_theme=str(state.get("cursor_theme") or ""),
        cursor_size=int(state.get("cursor_size") or 0),
        monitors=monitors,
    )
